name: Advent of Code Badges
on:
  workflow_dispatch:
  push:
    paths:
      - '2020*/'
jobs:
  build:
    name: Update badges
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: J0B10/aoc-badges-action@v3
        with:
          userid: 510966
          session: ${{ secrets.AOC_SESSION }}
          year: 2020
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2020%20stars%20â­-)[0-9]+(?=-yellow)'
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Update badges
          file_pattern: README.md
